### PR TITLE
Update: added new command (!version)

### PR DESCRIPTION
**Pull request by webgtx**
The print command of the current version, I think this is one of the most basic commands that should be here

### CODE REVIEW

**Comment by webgtx** [comment]
image

**Comment by AineeJames** [comment]
I really like this addition! However, I think that the the subprocess command may not work in some cases. For example if a user is not in a venv, then subprocess could fail since it would need to call 'pip3 show gpterminator' instead.

**Comment by AineeJames** [comment]
Perhaps we could use the __version__ attribute instead? (I have never before)

**Comment by webgtx** [comment]
Got you, wait for hot fixes

**Pull request closed without merging**
